function gamma = Gamma(params,q,q_dot)
%GAMMA
%    GAMMA = GAMMA(L_1,L_2,THETA_1,THETA_2,THETA_DOT_1,THETA_DOT_2,X_1,X_2,X_DOT_1,X_DOT_2,Y_1,Y_2,Y_DOT_1,Y_DOT_2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    24-Apr-2022 14:11:04
C_1 = params.C_1;
omega = params.omega;
L_1 = params.L_1;
L_2 = params.L_2;

x_1 = q(1);
y_1 = q(2);
theta_1 = q(3);
x_2 = q(4);
y_2 = q(5);
theta_2 = q(6);
x_dot_1 = q_dot(1);
y_dot_1 = q_dot(2);
theta_dot_1 = q_dot(3);
x_dot_2 = q_dot(4);
y_dot_2 = q_dot(5);
theta_dot_2 = q_dot(6);
t2 = abs(L_2);
t3 = cos(theta_2);
t4 = sin(theta_2);
t5 = theta_dot_1.^2;
t6 = theta_dot_2.^2;
t8 = -theta_2;
t7 = t2.^2;
t9 = t8+theta_1;
t10 = sin(t9);
t11 = t7.*(9.0./1.6e+1);
t12 = 1.0./sqrt(t11);
t13 = L_1.*L_2.*t10.*t12.*theta_dot_1.*(3.0./8.0);
gamma = [L_1.*t5.*cos(theta_1).*(-1.0./2.0);L_1.*t5.*sin(theta_1).*(-1.0./2.0);-theta_dot_2.*(t13-t12.*theta_dot_2.*(L_1.*L_2.*t10.*(3.0./8.0)-L_2.*t4.*(x_1-x_2).*(3.0./4.0)+L_2.*t3.*(y_1-y_2).*(3.0./4.0))-L_2.*t3.*t12.*x_dot_1.*(3.0./4.0)+L_2.*t3.*t12.*x_dot_2.*(3.0./4.0)-L_2.*t4.*t12.*y_dot_1.*(3.0./4.0)+L_2.*t4.*t12.*y_dot_2.*(3.0./4.0))+theta_dot_1.*(t13-L_1.*L_2.*t10.*t12.*theta_dot_2.*(3.0./8.0))+L_2.*t3.*t12.*theta_dot_2.*x_dot_1.*(3.0./4.0)-L_2.*t3.*t12.*theta_dot_2.*x_dot_2.*(3.0./4.0)+L_2.*t4.*t12.*theta_dot_2.*y_dot_1.*(3.0./4.0)-L_2.*t4.*t12.*theta_dot_2.*y_dot_2.*(3.0./4.0);L_2.*t3.*t6.*(-1.0./2.0);L_2.*t4.*t6.*(-1.0./2.0);0.0];
