function phit = Nu(params)
%NU
%    PHIT = NU(OMEGA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    24-Apr-2022 14:11:04
omega = params.omega;
phit = [0.0;0.0;0.0;0.0;0.0;omega];
