function phiq = Phi_q(params,q)
%PHI_Q
%    PHIQ = PHI_Q(L_1,L_2,THETA_1,THETA_2,X_1,X_2,Y_1,Y_2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    24-Apr-2022 14:11:04
C_1 = params.C_1;
omega = params.omega;
L_1 = params.L_1;
L_2 = params.L_2;

x_1 = q(1);
y_1 = q(2);
theta_1 = q(3);
x_2 = q(4);
y_2 = q(5);
theta_2 = q(6);

t2 = abs(L_2);
t3 = cos(theta_2);
t4 = sin(theta_2);
t6 = -theta_2;
t5 = t2.^2;
t7 = t6+theta_1;
t8 = cos(t7);
t9 = t5.*(9.0./1.6e+1);
t10 = 1.0./sqrt(t9);
t11 = L_2.*t3.*t10.*(3.0./4.0);
t12 = L_2.*t4.*t10.*(3.0./4.0);
phiq = reshape([1.0,0.0,-t12,0.0,0.0,0.0,0.0,1.0,t11,0.0,0.0,0.0,(L_1.*sin(theta_1))./2.0,L_1.*cos(theta_1).*(-1.0./2.0),L_1.*L_2.*t8.*t10.*(3.0./8.0),0.0,0.0,1.0,0.0,0.0,t12,1.0,0.0,0.0,0.0,0.0,-t11,0.0,1.0,0.0,0.0,0.0,-t10.*(L_1.*L_2.*t8.*(3.0./8.0)+L_2.*t3.*(x_1-x_2).*(3.0./4.0)+L_2.*t4.*(y_1-y_2).*(3.0./4.0)),(L_2.*t4)./2.0,L_2.*t3.*(-1.0./2.0),0.0],[6,6]);
