function phi = Phi(G,L_1,L_2,L_3,theta_2,theta_3,x_2,x_3,y_2,y_3)
%PHI
%    PHI = PHI(G,L_1,L_2,L_3,THETA_2,THETA_3,X_2,X_3,Y_2,Y_3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    08-May-2022 16:02:28

t2 = cos(theta_2);
t3 = cos(theta_3);
t4 = sin(theta_2);
t5 = sin(theta_3);
t6 = (L_2.*t2)./2.0;
t7 = (L_3.*t3)./2.0;
t8 = (L_2.*t4)./2.0;
t9 = (L_3.*t5)./2.0;
phi = [(t6-x_2).^2+(t8-y_2).^2-L_1.^2;t6+t7+x_2-x_3;t8+t9+y_2-y_3;-G+t7+x_3;t9+y_3];
