function gamma = Gamma(params,q,q_dot)
%GAMMA
%    GAMMA = GAMMA(L_2,L_3,THETA_2,THETA_3,THETA_DOT_2,THETA_DOT_3,X_2,X_DOT_2,Y_2,Y_DOT_2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    08-May-2022 16:02:29

L_2 = params.L2;
L_3 = params.L3;
theta_2 = q(3);
theta_3 = q(6);
theta_dot_2 = q_dot(3);
theta_dot_3 = q_dot(6);
x_2 = q(1);
x_dot_2 = q_dot(1);
y_2 = q(2);
y_dot_2 = q_dot(2);

t2 = cos(theta_2);
t3 = cos(theta_3);
t4 = sin(theta_2);
t5 = sin(theta_3);
t6 = L_2.^2;
t7 = theta_dot_2.^2;
t8 = theta_dot_3.^2;
t9 = (L_3.*t3.*t8)./2.0;
t10 = (L_3.*t5.*t8)./2.0;
gamma = [-theta_dot_2.*(theta_dot_2.*((t2.^2.*t6)./2.0+(t4.^2.*t6)./2.0+L_2.*t2.*(x_2-(L_2.*t2)./2.0)+L_2.*t4.*(y_2-(L_2.*t4)./2.0))+L_2.*t4.*x_dot_2-L_2.*t2.*y_dot_2)-x_dot_2.*(x_dot_2.*2.0+L_2.*t4.*theta_dot_2)-y_dot_2.*(y_dot_2.*2.0-L_2.*t2.*theta_dot_2);t9+(L_2.*t2.*t7)./2.0;t10+(L_2.*t4.*t7)./2.0;t9;t10];
