function gamma = Gamma(L_1,L_2,theta_1,theta_2,theta_dot_1,theta_dot_2,x_1,x_2,x_dot_1,x_dot_2,y_1,y_2,y_dot_1,y_dot_2)
%GAMMA
%    GAMMA = GAMMA(L_1,L_2,THETA_1,THETA_2,THETA_DOT_1,THETA_DOT_2,X_1,X_2,X_DOT_1,X_DOT_2,Y_1,Y_2,Y_DOT_1,Y_DOT_2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    24-Apr-2022 13:48:48

t2 = abs(L_2);
t3 = cos(theta_1);
t4 = cos(theta_2);
t5 = sin(theta_1);
t6 = sin(theta_2);
t7 = theta_dot_1.^2;
t8 = theta_dot_2.^2;
t9 = t2.^2;
t10 = t3.*t4;
t11 = t5.*t6;
t12 = t9.*(9.0./4.0);
t13 = t10+t11;
t14 = 1.0./sqrt(t12);
t15 = L_1.*L_2.*t13.*t14.*theta_dot_1.*(3.0./4.0);
gamma = [L_1.*t3.*t7.*(-1.0./2.0);L_1.*t5.*t7.*(-1.0./2.0);theta_dot_2.*(t15-t14.*theta_dot_2.*(L_1.*L_2.*t13.*(3.0./4.0)+L_2.*t6.*(x_1-x_2).*(3.0./2.0)-L_2.*t4.*(y_1-y_2).*(3.0./2.0))+L_2.*t4.*t14.*x_dot_1.*(3.0./2.0)-L_2.*t4.*t14.*x_dot_2.*(3.0./2.0)+L_2.*t6.*t14.*y_dot_1.*(3.0./2.0)-L_2.*t6.*t14.*y_dot_2.*(3.0./2.0))-theta_dot_1.*(t15-L_1.*L_2.*t13.*t14.*theta_dot_2.*(3.0./4.0))+L_2.*t4.*t14.*theta_dot_2.*x_dot_1.*(3.0./2.0)-L_2.*t4.*t14.*theta_dot_2.*x_dot_2.*(3.0./2.0)+L_2.*t6.*t14.*theta_dot_2.*y_dot_1.*(3.0./2.0)-L_2.*t6.*t14.*theta_dot_2.*y_dot_2.*(3.0./2.0);L_2.*t4.*t8.*(-1.0./2.0);L_2.*t6.*t8.*(-1.0./2.0);0.0];
