function phi = Phi(C_1,L_1,L_2,omega,t,theta_1,theta_2,x_1,x_2,y_1,y_2)
%PHI
%    PHI = PHI(C_1,L_1,L_2,OMEGA,T,THETA_1,THETA_2,X_1,X_2,Y_1,Y_2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    24-Apr-2022 13:48:48

t2 = cos(theta_1);
t3 = cos(theta_2);
t4 = sin(theta_1);
t5 = sin(theta_2);
phi = [x_1-(L_1.*t2)./2.0;y_1-(L_1.*t4)./2.0;-1.0./sqrt(abs(L_2).^2.*(9.0./4.0)).*(L_2.^2.*(3.0./8.0)+L_2.*t5.*(x_1-x_2).*(3.0./2.0)-L_2.*t3.*(y_1-y_2).*(3.0./2.0)+L_1.*L_2.*(t2.*t3+t4.*t5).*(3.0./4.0))-2.0;C_1+x_2-(L_2.*t3)./2.0;y_2-(L_2.*t5)./2.0;theta_1-omega.*t];
