function phi = Phi(params,t,q)
%PHI
%    PHI = PHI(C_1,L_1,L_2,OMEGA,T,THETA_1,THETA_2,X_1,X_2,Y_1,Y_2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    24-Apr-2022 14:11:04
C_1 = params.C_1;
omega = params.omega;
L_1 = params.L_1;
L_2 = params.L_2;

x_1 = q(1);
y_1 = q(2);
theta_1 = q(3);
x_2 = q(4);
y_2 = q(5);
theta_2 = q(6);

t2 = cos(theta_2);
t3 = sin(theta_2);
phi = [x_1-(L_1.*cos(theta_1))./2.0;y_1-(L_1.*sin(theta_1))./2.0;1.0./sqrt(abs(L_2).^2.*(9.0./1.6e+1)).*(L_1.*L_2.*sin(theta_1-theta_2).*(3.0./8.0)-L_2.*t3.*(x_1-x_2).*(3.0./4.0)+L_2.*t2.*(y_1-y_2).*(3.0./4.0))+2.0;C_1+x_2-(L_2.*t2)./2.0;y_2-(L_2.*t3)./2.0;theta_1-omega.*t];
